version: '3'

services: 
  sofomoapp:
    build: 
      context: .
      dockerfile: Dockerfile-local
    volumes:
      - .:/opt/apps/sofomoapp/src
    networks: 
      - nginx_network
      - dbservice_network
    depends_on: 
      - dbservice
    command: sh -c "sofomoapp/manage.py migrate && sofomoapp/manage.py collectstatic --noinput && gunicorn --chdir sofomoapp --bind :8000 sofomoapp.wsgi:application"

  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      - .:/opt/apps/sofomoapp/src
    depends_on:
      - sofomoapp
    networks: 
      - nginx_network
    
  dbservice:
    image: postgres:latest
    env_file:
      - config/db/dbservice_env
    volumes: 
      - dbservice_volume:/var/lib/postgresql/data
    networks: 
      - dbservice_network

networks:
  dbservice_network:
    driver: bridge
  nginx_network:
    driver: bridge

volumes:
  dbservice_volume: